# Generated by Django 5.2 on 2025-05-04 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storemanager',
            unique_together=set(),
        ),
    ]
