# Generated by Django 5.2 on 2025-05-10 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_alter_productreview_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('session_id', 'is_active')},
        ),
    ]
